

# The name of this app. Must be unique within a project.
name: app

type: 'ruby:2.7'


mounts:
    log:
      source: local
      source_path: log
    tmp:
      source: local
      source_path: tmp


relationships:
    postgresdatabase: 'dbpostgres:postgresql'


# The size of the persistent disk of the application (in MB).
disk: 1024


hooks:
    build: |
      gem install bundler:2.2.8
      bundle install --without development test
      RAILS_ENV=production bundle exec rake assets:precompile
    deploy: |
      RAILS_ENV=production bundle exec rake db:migrate 

web:
  upstream: 
    socket_family: "unix"
  commands: 
    start: "unicorn -l $SOCKET -E production config.ru"
  locations: 
    '/': 
      root: "public"
      passthru: true
      expires: 1h
      allow: true

